### ISSUE TITLE
shift/reduce conflict

### ISSUE THREAD

**Issue by ziscky** [bdhobare/Compiler#1]
Shift reduce conflict for the calc.y grammar spec.
Relevant output of yacc -v:

7: shift/reduce conflict (shift 5, reduce 4) on '+'
7: shift/reduce conflict (shift 6, reduce 4) on '-'
state 7
	expr : expr . '+' expr  (4)
	expr : expr '+' expr .  (4)
	expr : expr . '-' expr  (5)

	'+'  shift 5
	'-'  shift 6
	'\n'  reduce 4

8: shift/reduce conflict (shift 5, reduce 5) on '+'
8: shift/reduce conflict (shift 6, reduce 5) on '-'
state 8
	expr : expr . '+' expr  (4)
	expr : expr . '-' expr  (5)
	expr : expr '-' expr .  (5)

	'+'  shift 5
	'-'  shift 6
	'\n'  reduce 5

**Comment by bdhobare** [comment]
I have solved it by defining a left associativity rule for + and -
